#!/usr/bin/env python3
"""Generates lib/fonts.js — the webfonts, embedded.

The confirm page is deliberately self-contained: the customer opens it on a
phone, often on mobile data, straight after an installer hands them the screen,
and a page that needs a second host to look right is a page that can arrive
looking broken. Loading Exo 2 and Inter from Google would also hand a third
party the IP and user-agent of someone viewing their own name, phone, email and
installation address.

So the faces are subsetted, converted to WOFF2 and baked into the stylesheet as
data URIs. The sources are the exact TTFs the mobile app bundles
(feston/assets/fonts), which is what makes the link look like the app that
handed it over.

Re-run after changing a weight or a source file:

    python -m pip install fonttools brotli
    python scripts/build-fonts.py

Only weights the stylesheet actually draws are built — an unused face is pure
weight on the one request the page gets.
"""

import base64
import io
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
FUNCTIONS = os.path.dirname(HERE)
# feston care/festonphase4-confirmurl/functions/scripts -> feston care
ROOT = os.path.dirname(os.path.dirname(FUNCTIONS))
SRC = os.path.join(ROOT, "feston", "assets", "fonts")
OUT = os.path.join(FUNCTIONS, "lib", "fonts.js")

# Google's own "latin" range. Its "latin-ext" companion is deliberately left
# out: it more than doubles Inter (17 KB -> 41 KB per weight) to cover Eastern
# European and Vietnamese letters this page will not see. Google serves the two
# as separate files and fetches latin-ext only when a character needs it —
# inlining means paying for it on every open instead. Latin-1 already carries
# the accents that turn up in a customer name; past that a name falls back to
# the system font, exactly as a Tamil or Devanagari one does today.
LATIN = (
    "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,"
    "U+0304,U+0308,U+0329,U+2000-206F,U+2074,U+20AC,U+2122,U+2191,U+2193,"
    "U+2212,U+2215,U+FEFF,U+FFFD"
)

# Headings are our own fixed copy, never customer text, so Exo 2 needs only the
# characters this page can emit.
HEADING_RANGE = "U+0020-007E,U+00A0-00FF,U+2013-2014,U+2018-201D,U+2022,U+00B7"
BODY_RANGE = LATIN

FACES = [
    ("Exo 2", 600, "Exo2-SemiBold.ttf", HEADING_RANGE),
    ("Inter", 400, "Inter-Regular.ttf", BODY_RANGE),
    ("Inter", 500, "Inter-Medium.ttf", BODY_RANGE),
]


def subset(path, unicodes, out_path):
    subprocess.run(
        [
            sys.executable,
            "-m",
            "fontTools.subset",
            path,
            "--unicodes=" + unicodes,
            "--layout-features=kern,liga,calt",
            "--flavor=woff2",
            "--desubroutinize",
            "--no-hinting",
            "--drop-tables+=DSIG",
            "--output-file=" + out_path,
        ],
        check=True,
        stdout=subprocess.DEVNULL,
    )


def main():
    rules = []
    total = 0

    with tempfile.TemporaryDirectory() as tmp:
        for family, weight, filename, unicodes in FACES:
            src = os.path.join(SRC, filename)
            if not os.path.exists(src):
                raise SystemExit("missing source font: " + src)

            dest = os.path.join(tmp, filename + ".woff2")
            subset(src, unicodes, dest)

            data = open(dest, "rb").read()
            total += len(data)
            b64 = base64.b64encode(data).decode("ascii")
            print("%-20s %6d bytes woff2  (from %d)" % (filename, len(data), os.path.getsize(src)))

            rules.append(
                "@font-face{font-family:'%s';font-style:normal;font-weight:%d;"
                "font-display:swap;src:url(data:font/woff2;base64,%s) format('woff2')}"
                % (family, weight, b64)
            )

    banner = (
        "// GENERATED by scripts/build-fonts.py — do not edit by hand.\n"
        "//\n"
        "// Exo 2 and Inter, subsetted and embedded as WOFF2 data URIs so the confirm\n"
        "// page stays self-contained: no request to fonts.googleapis.com from a page\n"
        "// showing a customer their own name, phone and address, and nothing to fail\n"
        "// on a weak mobile connection.\n"
        "//\n"
        "// Sourced from the TTFs the mobile app bundles (feston/assets/fonts), so the\n"
        "// link a customer opens is set in the same faces as the app that sent it.\n"
        "//\n"
        "// Only the weights the stylesheet draws are here. Adding a font-weight to\n"
        "// page.js means adding its face to FACES in the build script and re-running.\n"
        "\n'use strict';\n\n"
    )

    body = "const FONT_FACE_CSS = `\n" + "\n".join(rules) + "\n`;\n\nmodule.exports = { FONT_FACE_CSS };\n"

    io.open(OUT, "w", encoding="utf-8", newline="\r\n").write(banner + body)
    print("\n%s  (%d bytes woff2, %d bytes base64 in the page)" % (OUT, total, total * 4 // 3))


if __name__ == "__main__":
    main()
